### ISSUE TITLE
Paragraph tests failing in ckeditor5 CI

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-paragraph#20]
See https://travis-ci.org/ckeditor/ckeditor5/builds/221381113

```
FAILED TESTS:
  Paragraph feature – integration
    with clipboard
      ✖ pastes h1+h2+p as p+p+p when heading feature is not present
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45675:26)

      ✖ pastes h1+h2+p as p+h2+p when heading feature is present
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45694:26)

      ✖ pastes ul>li+li as p+p when list feature is not present
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45712:26)

      ✖ pastes ul>li>h2+h3+p as h2+h3+p when heading feature is present
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45732:26)

      ✖ pastes ul>li>ul>li+li
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45755:26)

      ✖ pastes ul>li>p,text
        Chrome 57.0.2987 (Mac OS X 10.12.4)
      TypeError: Cannot read property 'getData' of undefined
          at Document.listenTo (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45294:21)
          at Document.fire (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:2419:29)
          at __WEBPACK_IMPORTED_MODULE_3__ckeditor_ckeditor5_core_tests_utils_virtualtesteditor__.a.create.then.newEditor (packages/ckeditor5-paragraph/tests/paragraph-intergration.js:45778:26)
```

**Comment by oleq** [comment]
I see that tests in Paragraph CI also fail https://travis-ci.org/ckeditor/ckeditor5-paragraph/builds/220849338. They were green until I restarted the build, which means that some external change is behind it.

**Comment by Reinmar** [comment]
When you want to know what change in what package caused some other tests to fail it's useful to go to https://github.com/ckeditor/ckeditor5/commits/master-revisions. There you have it :)

BTW, I'd like to plug notifications from that branch's CI to our Slack :) I can see that it might help us a lot.

**Comment by oleq** [comment]
That would certainly help us a lot!

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-paragraph/commit/a8043487f307cc68d8f1cb54e69c8866565b9386.
